name: Deploy Portfolio

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python & uv
      uses: astral-sh/setup-uv@v3
      with:
        python-version: "3.13"

    - name: Run Tests
      run: |
        PYTHONPATH=. uv run pytest

    - name: Google Auth
      if: success()
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Docker Auth'
      run: |-
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev

    - name: Build and Push Container
      run: |-
        docker build -t "asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/portfolio-repo/api:${{ github.sha }}" .
        docker push "asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/portfolio-repo/api:${{ github.sha }}"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Terraform Apply
      working-directory: ./infra
      run: |
        terraform init
        terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
