/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./html/**/*.html",
    "./js/**/*.js",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#505253",
        "surface-tint": "#5f5e5e",
        "outline": "#887863",
        "background": "#ebe0d5",
        "tertiary": "#486272",
        "on-tertiary": "#f4faff",
        "on-background": "#3c301f",
        "surface-dim": "#edd7ba",
        "on-tertiary-fixed": "#2c4655",
        "tertiary-fixed": "#d0ecff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#fe8983",
        "secondary-container": "#e2e2e3",
        "primary-container": "#e5e2e1",
        "on-error": "#fff7f6",
        "on-secondary-fixed-variant": "#5a5c5d",
        "primary-dim": "#535252",
        "inverse-on-surface": "#a59b92",
        "surface-container": "#fbebd9",
        "error": "#9f403d",
        "inverse-surface": "#120d08",
        "secondary-fixed-dim": "#d3d4d5",
        "on-primary-container": "#525151",
        "on-secondary-fixed": "#3d4041",
        "inverse-primary": "#ffffff",
        "on-primary-fixed-variant": "#5c5b5b",
        "on-error-container": "#752121",
        "primary": "#5f5e5e",
        "on-primary": "#faf7f6",
        "primary-fixed": "#e5e2e1",
        "secondary-dim": "#515354",
        "surface-bright": "#fff8f3",
        "on-primary-fixed": "#403f3f",
        "surface-container-high": "#f8e5d0",
        "tertiary-fixed-dim": "#c2def0",
        "secondary-fixed": "#e2e2e3",
        "surface-container-highest": "#f4dfc6",
        "on-surface-variant": "#6b5d49",
        "on-tertiary-container": "#3e5868",
        "on-tertiary-fixed-variant": "#486272",
        "tertiary-container": "#d0ecff",
        "outline-variant": "#c2af98",
        "surface-container-low": "#fff1e3",
        "tertiary-dim": "#3c5666",
        "on-secondary": "#f8f9fa",
        "secondary": "#5d5f60",
        "on-surface": "#3c301f",
        "surface-variant": "#f4dfc6",
        "error-dim": "#4e0309",
        "surface": "#fff8f3",
        "primary-fixed-dim": "#d6d4d3"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
